version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: zuora-poc-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: zuora_poc
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - zuora-network

volumes:
  mongodb_data:

networks:
  zuora-network:
    driver: bridge